import viking from "../../assets/11.png"
import onememoji from "../../assets/1.png"
import twomemoji from "../../assets/6.png"
import threememoji from "../../assets/8.png"
import fourmemoji from "../../assets/12.png"
import fifthmemoji from "../../assets/3.png"
import sixmemoji from "../../assets/10.png"
import sevmemoji from "../../assets/4.png"

export const feedData = [
    {
        id: 1,
        name: "David Glover",
        date: "Sep 22",
        profile: sixmemoji,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--KM-M3aSO--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/t05ipvoixkrha72iwp0p.jpg",
        heading: "🚀 #3 Golang Projects that makes you PRO",
        reactions: 4,
        read: 4,
        bio:"On a mission to make online learning less boring. Coding live on LonePine.com",
        color:"bg-blue-500",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
        Location: "Accra",
        Education: "Bsc Physics",
        Work: "Full-stack Developer",
        Joined:"Nov 2020",
        comments: 10,
        tags: [{ id: 9, tech: "Golang" }, { id: 10, tech: "Backend" }, { id: 11, tech: "webdev" }, { id: 12, tech: "newbie" }]
    },
    {
        id: 2,
        name: "Sam Lokko",
        date: "Sep 18",
        profile: onememoji,
        heading: "😡 Fine...you want CSS art you got it! 💪 My first ever CSS art.",
        reactions: 5,
        read: 8,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--lJASVMu8--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/h0zyh4d4454kru3u8pra.png",
        bio:"Discussions. 💬 Tools. 🛠 Resources. 📚 All things productivity. 🎯🚀💯 ",
        color:"bg-yellow-500",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
        Location: "Manchester",
        Education: "Electrical Engineering",
        Work: "Mobile Engineering",
        Joined:"Aug 2019",
        comments: 22, tags: [{ id: 9, tech: "css" }, { id: 10, tech: "art" }, { id: 11, tech: "showdev" }, { id: 12, tech: "newbie" }]
    },
    {
        id: 3,
        name: "Fatima Mukesh",
        date: "Sep 17",
        profile: twomemoji,
        heading: "Top 10 Common Types of Cyber Security Attacks",
        reactions: 10,
        read: 7,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--bSrpNb_N--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/5dsa8cf7o8t07593sb83.jpg",
        bio:"I'm a freelance open source developer, hacking my way through code. ",
        color:"bg-indigo-500",
        description:"Lorem ipsum dolor sit amet consecteturadipisicing elit.\nIure eligendi harum ea, amet quodlabore sunt dolor vero sapiente.\nEos quae facere aliasvoluptatibus labore provident non quasi laudantium, velitsunt facilis odit enim maxime atque.\nRem repellatveritatis, tenetur voluptatem quod alias magni maioresquibusdam laboriosam perspiciatis doloremque eos!",
        Location: "Seattle",
        Education: "Computer Science",
        Work: "Network Engineer",
        Joined:"Feb 2021",
         comments: 2,
          tags: [{ id: 9, tech: "security" }, { id: 10, tech: "protection" }, { id: 11, tech: "beginners" }]
    },
    {
        id: 4,
        name: "Fiona Jackson",
        date: "Sep 17",
        profile: threememoji,
        heading: "How to pick an open-source project to contribute to? ",
        reactions: 5,
        read: 8,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--bsIFcD6r--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/6kmee04y9c18bfmeup8i.jpg",
        bio:"Building products is my profession, Creating content is my passion.",
        color:"bg-red-500",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
        Location: "Berlin",
        Education: "Computer Engineering",
        Work: "Frontend Developer",
        Joined:"August 2020",
        comments: 2,
        tags: [{ id: 9, tech: "opensource" }, { id: 10, tech: "hacktoberfest" }, { id: 11, tech: "webdev" }, { id: 12, tech: "newjob" }]
    },
    {
        id: 5,
        name: "Adara Chukwu",
        date: "Sep 16",
        profile: fourmemoji,
        heading: "🚀10 Trending projects on GitHub for web developers ",
        reactions: 8,
        read: 4,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--twKmu1Yw--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://thepracticaldev.s3.amazonaws.com/i/rj8fisrei0754velkkpx.jpeg",
        bio:"No ads, No BS just some good content sent directly to your inbox. ",
        color:"bg-pink-500",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
        Location: "Lagos",
        Education: "Data Analyst",
        Work: "UI/UX Designer",
        Joined:"May 2019",
        comments: 3,
        tags: [{ id: 9, tech: "productivity" }, { id: 10, tech: "github" }, { id: 11, tech: "react" }, { id: 12, tech: "webdev" }]
    },
    {
    id: 6,
    name:"Patricia Sesil",
    date: "Sep 14",
    profile: fifthmemoji,
    heading:"BINARY SEARCH",
    reactions:100,
        read: 7,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--dMSu-hlY--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/art8pqjemlbgjj4w96di.jpg",
        bio:"Author at CSS-Tricks. A Front-end Enthusiast, a programmer, a problem solver and a human being who tries to keep a good relationship with bugs! ",
    color:"bg-red-500",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
    Location: "Nairobi",
    Education: "Computer Science",
    Work: "Software Engineer",
    Joined:"July 2021",
    comments:1,
    tags:[{ id:9,tech:"algorithms"}, {id:10, tech: "binary"}, { id:11,tech:"cpp"},{id:12,tech:"beginner"}]},
    {
    id: 7,
    name:"Sam Hackman",
    date:"Sep 14",
    profile: viking, heading: "Open Source Community: How to Become an Active Contributor ",
    reactions: 3,
        read: 12,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--gddsX_Tq--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/4cf64a8f018tdpbb6z4c.PNG",
        bio:"A Front-end developer, that is passionate about web accessibility. ",
    color:"bg-gray-500",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
    Location: "New York",
    Education: "Statistics",
    Work: "Software Architect",
    Joined:"Dec 2020",
    comments:2,
    tags:[{ id:9,tech:"opensource"}, {id:10, tech: "newbie"}, { id:11,tech:"job"},{id:12,tech:"community"}]},
    {
    id:8,
    name:"Nicole FiedMan",
    date: "Sep 11",
    profile: sevmemoji,
    heading:"7 Best Tools For Developers ⚙⚙ ",
    reactions: 10,
        read: 2,
        image:"https://res.cloudinary.com/practicaldev/image/fetch/s--RL2pD8F5--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/sw6ip1bqfjfh5gwg1yjn.png",
        bio:"Looking to get into development? As a full-stack developer I guide you on this journey and give you bite sized tips every single day 👊 ",
    color:"bg-pink-500",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.\nIure eligendi harum ea, amet quod labore sunt dolor vero sapiente.\nEos quae facere alias voluptatibus labore provident non quasi laudantium, velit sunt facilis odit enim maxime atque.\nRem repellat veritatis, tenetur voluptatem quod alias magni maiores quibusdam laboriosam perspiciatis doloremque eos!",
    Location: "London",
    Education: "Bsc Mathematics",
    Work: "API Developer",
    Joined:"Jan 2021",
    comments:3,
    tags:[{ id:9,tech:"productivity"}, {id:10, tech: "learn"}, { id:11,tech:"php"},{id:12,tech:"community"}]},
   
]

export const getSinglePost = (id) => {
    return feedData.find(data=>data.id === id)
}